apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command: ['sh','-c', 'ls && sleep 3600']
    image: busybox
    name: busybox1
  - command: ['sh','-c', 'echo "Hello world" && sleep 3600']
    image: busybox
    name: busybox2
  - command: ['sh','-c', 'echo "This is the third containter" && sleep 3600']
    image: busybox
    name: busybox3
