apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-cont-pod
  name: multi-cont-pod
spec:
  containers:
  - image: busybox
    name: main
    command: ['sh','-c','while true; do echo "Hi I am from main container" >> /var/log/index.html; sleep 5; done']
    volumeMounts:
    - mountPath: /var/log
      name: mainvol
  - image: nginx
    name: sidecar
    ports:
            - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: sidecarvol
  volumes:
  - name: mainvol
    emptyDir: {}
  - name: sidecarvol
    emptyDir: {}
