apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-nodeselector
  name: nginx-nodeselector
spec:
  nodeSelector:
    kubernetes.io/hostname: kubenode02
  containers:
  - image: nginx
    name: nginx-nodeselector
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
