apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-5
spec:
  containers:
  - name: sec-ctx-5
    image: nginx
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi
