apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-envvar
spec:
  containers:
    - name: nginx-env
      image: nginx
      env:
        - name: secret_username 
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: user
        - name: secret_password
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password

